### ISSUE TITLE
Not working with Carthage installation

### ISSUE THREAD

**Issue by carmen-gh** [PiXeL16/IBLocalizable#14]
I wanted to use IBLocalizable with option to install via Carthage, but it didn't work.
Tried it in a small sample App.
Tried the same with the CocoaPods installation and it worked.

**Comment by PiXeL16** [comment]
Yeah, not sure what happened with Carthage. Do you have ideas? I don't really have a lot of time to dig into the project anymore. PRs are very welcome.

**Comment by carmen-gh** [comment]
I have no idea, but I will have a closer look. If I find a solution I will create a PR

**Comment by ktakayama** [comment]
#16 will be fix of this problem.

**Comment by PiXeL16** [comment]
I just merged #16 @camina-apps can you give it another try and report back if that works?

**Comment by carmen-gh** [comment]
@ktakayama @PiXeL16 still not working. I tried it with Xcode 9.3 and IBLocalizable 1.2.0
<img width="262" alt="screenshot" src="https://user-images.githubusercontent.com/7295014/39543432-821385b6-4e4b-11e8-8a53-9811886fc350.png">

**Comment by carmen-gh** [comment]
Seems it is a general problem https://github.com/Carthage/Carthage/issues/335 
https://openradar.appspot.com/23114017
https://stackoverflow.com/questions/29933691/ibdesignable-from-external-framework/37631860#37631860

**Comment by PiXeL16** [comment]
I see, thanks for the research. I will let this one open in case others find it useful.

**Comment by ktakayama** [comment]
@camina-apps 
`IBLocalizable 1.2.0` does not contain #16 .
Please try this in your Cartfile.

```
github "PiXeL16/IBLocalizable" "f1c072437472684d4dc4560678283743112e5f73"
```

**Comment by PiXeL16** [comment]
@ktakayama Not sure if I understand. `Carthage` its supposed to pull from master no?. And that should contain #16?. `1.2.0` it's the release version that its mostly used by the `Podfile` I believe.

**Comment by ktakayama** [comment]
Carthage will not build from master if you tagged any revision.

```
$ ls
Cartfile
$ cat Cartfile
github "PiXeL16/IBLocalizable"

$ carthage bootstrap --platform iOS
*** No Cartfile.resolved found, updating dependencies
*** Fetching IBLocalizable
*** Checking out IBLocalizable at "1.2.0"
*** xcodebuild output can be found in /var/folders/z5/br6wh4sd2n94072swvtchkk80000gn/T/carthage-xcodebuild.sZRBBh.log
*** Building scheme "IBLocalizable" in IBLocalizable.xcworkspace

$ ls
Cartfile  Cartfile.resolved  Carthage/

$ cat Cartfile.resolved
github "PiXeL16/IBLocalizable" "1.2.0"
```


```
$ ls
Cartfile

$ cat Cartfile
github "PiXeL16/IBLocalizable" "f1c072437472684d4dc4560678283743112e5f73"

$ carthage bootstrap --platform iOS
*** No Cartfile.resolved found, updating dependencies
*** Checking out IBLocalizable at "f1c072437472684d4dc4560678283743112e5f73"
*** xcodebuild output can be found in /var/folders/z5/br6wh4sd2n94072swvtchkk80000gn/T/carthage-xcodebuild.yh9QeT.log
*** Building scheme "IBLocalizable" in IBLocalizable.xcworkspace

$ ls
Cartfile  Cartfile.resolved  Carthage/

$ cat Cartfile.resolved
github "PiXeL16/IBLocalizable" "f1c072437472684d4dc4560678283743112e5f73"
```

**Comment by ktakayama** [comment]
The solution(#16) for this issue is the same way as HeroTransitions/HERO....
https://github.com/HeroTransitions/Hero/issues/307

**Comment by carmen-gh** [comment]
@ktakayama still not working. this has to be fixed https://openradar.appspot.com/23114017 by Apple. I even tried HeroTransition and it is not working for them ether
